# Day 2 — Pandas Capstone Project

Track C — ML Fundamentals

This notebook demonstrates loading, inspecting, cleaning, filtering, grouping, and summarizing a dataset using pandas.

In [1]:
import pandas as pd
import numpy as np

## 1. Create and inspect a dataset

In [2]:
data = {
    'name': ['Asha', 'Ravi', 'Neha', 'Kabir', 'Meera', 'Ishaan', 'Sara', 'Dev'],
    'city': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Pune'],
    'age': [18, 19, 17, 20, 18, 21, 19, 18],
    'math_marks': [78, 85, 91, 67, 88, 73, np.nan, 95],
    'science_marks': [82, 79, 94, 72, np.nan, 81, 89, 96]
}
df = pd.DataFrame(data)
df.head()

    name    city  age  math_marks  science_marks
0   Asha   Delhi   18        78.0           82.0
1   Ravi  Mumbai   19        85.0           79.0
2   Neha    Pune   17        91.0           94.0
3  Kabir   Delhi   20        67.0           72.0
4  Meera    Pune   18        88.0            NaN

In [3]:
print('Shape:', df.shape)
print('\nDataFrame information:')
df.info()
print('\nSummary statistics:')
display(df.describe(numeric_only=True))

Shape: (8, 5)

DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8 non-null      object
 1   city           8 non-null      object
 2   age            8 non-null      int64
 3   math_marks     7 non-null      float64
 4   science_marks  7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

Summary statistics:

TypeError: NDFrame.describe() got an unexpected keyword argument 'numeric_only'

## 2. Check missing values

In [4]:
print(df.isnull().sum())

name             0
city             0
age              0
math_marks       1
science_marks    1
dtype: int64

## 3. Clean missing values

In [5]:
df_clean = df.copy()
df_clean['math_marks'] = df_clean['math_marks'].fillna(df_clean['math_marks'].mean())
df_clean['science_marks'] = df_clean['science_marks'].fillna(df_clean['science_marks'].mean())
print('Missing values after cleaning:')
print(df_clean.isnull().sum())
display(df_clean)

Missing values after cleaning:
name             0
city             0
age              0
math_marks       0
science_marks    0
dtype: int64

     name    city  age  math_marks  science_marks
0    Asha   Delhi   18   78.000000      82.000000
1    Ravi  Mumbai   19   85.000000      79.000000
2    Neha    Pune   17   91.000000      94.000000
3   Kabir   Delhi   20   67.000000      72.000000
4   Meera    Pune   18   88.000000      84.714286
5  Ishaan  Mumbai   21   73.000000      81.000000
6    Sara   Delhi   19   82.428571      89.000000
7     Dev    Pune   18   95.000000      96.000000

## 4. Create total and average scores

In [6]:
df_clean['total_marks'] = df_clean['math_marks'] + df_clean['science_marks']
df_clean['average_marks'] = df_clean[['math_marks', 'science_marks']].mean(axis=1)
display(df_clean[['name', 'math_marks', 'science_marks', 'total_marks', 'average_marks']])

     name  math_marks  science_marks  total_marks  average_marks
0    Asha   78.000000      82.000000   160.000000      80.000000
1    Ravi   85.000000      79.000000   164.000000      82.000000
2    Neha   91.000000      94.000000   185.000000      92.500000
3   Kabir   67.000000      72.000000   139.000000      69.500000
4   Meera   88.000000      84.714286   172.714286      86.357143
5  Ishaan   73.000000      81.000000   154.000000      77.000000
6    Sara   82.428571      89.000000   171.428571      85.714286
7     Dev   95.000000      96.000000   191.000000      95.500000

## 5. Filter students with average marks of at least 85

In [7]:
high_performers = df_clean[df_clean['average_marks'] >= 85]
display(high_performers[['name', 'city', 'average_marks']])

    name   city  average_marks
2   Neha   Pune      92.500000
4  Meera   Pune      86.357143
6   Sara  Delhi      85.714286
7    Dev   Pune      95.500000

## 6. Group by city and calculate average marks

In [8]:
city_summary = df_clean.groupby('city')[['math_marks', 'science_marks', 'average_marks']].mean().round(2)
display(city_summary)

        math_marks  science_marks  average_marks
city
Delhi        75.81          81.00          78.40
Mumbai       79.00          80.00          79.50
Pune         91.33          91.57          91.45

## 7. Sort students by average marks

In [9]:
ranked_students = df_clean.sort_values('average_marks', ascending=False)
display(ranked_students[['name', 'city', 'average_marks']])

     name    city  average_marks
7     Dev    Pune      95.500000
2    Neha    Pune      92.500000
4   Meera    Pune      86.357143
6    Sara   Delhi      85.714286
1    Ravi  Mumbai      82.000000
0    Asha   Delhi      80.000000
5  Ishaan  Mumbai      77.000000
3   Kabir   Delhi      69.500000

## 8. Final findings

- Missing numeric values were filled using the column mean to retain all students.
- New features (`total_marks` and `average_marks`) were created.
- Students were filtered by average score and ranked.
- City-level averages were calculated using `groupby()`.

### Reflection

The project relies on `DataFrame`, `isnull()`, `fillna()`, column selection, filtering, feature creation, `groupby()`, `mean()`, and `sort_values()`. For a real dataset, I would verify data quality, check duplicates and outliers, document cleaning choices, and visualize patterns before drawing conclusions.